image: node:6

cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
  - node_modules/
  - bower_components/

before_script:
  - npm config set cache /cache/npm
  - npm install --silent

pages:
  stage: deploy
  script:
    - npm run bower:install
    - npm run build:prod
    - mv dist public
  artifacts:
    paths:
    - public
  only:
  - $BRANCH
  tags:
    - docker
