stages:
  - test
  - deploy

test:
  image: alpine:latest
  stage: test
  script:
  - echo 'Testing'
  except:
  - tags

deploy:staging:
  image: alpine:latest
  stage: deploy
  script:
  - echo 'Deploying to staging'
  - cat public/index.html
  only:
  - master

deploy:production:
  image: alpine:latest
  stage: deploy
  script:
  - echo 'Deploying to production'
  - cat public/index.html
  when: manual
  only:
  - master


