stages:
  - test
  - release
  - deploy

test:
  image: alpine:latest
  stage: test
  script:
  - echo 'Testing'
  except:
  - tags

release:
  image: alpine:latest
  stage: release
  script:
  - TAG=$(date +%s)
  - git tag $TAG
  only:
  - master

deploy:staging:
  image: alpine:latest
  stage: deploy
  script:
  - echo 'Deploying to staging'
  - cat public/index.html
  only:
  - tags

deploy:production:
  image: alpine:latest
  stage: deploy
  script:
  - echo 'Deploying to production'
  - cat public/index.html
  when: manual
  only:
  - master


