image: alpine:latest

pages:
  stage: deploy
  script:
    # gzip all content
  - gzip -k -6 $(find public -type f)
  - echo $CI_PAGES_URL
  artifacts:
    paths:
    - public
    expire_in: 1 day
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
