image: node:6

cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
  - node_modules/
  - bower_components/

#before_script:
#  - npm config set cache /cache/npm
#  - npm install --silent


pages:
  stage: deploy
  script:
    - if [ $CI_BUILD_REF_NAME = $BRANCH ]; then npm config set cache /cache/npm && npm install --silent && npm install -g bower gulp-cli && npm install gulp wrench; fi
    - if [ $CI_BUILD_REF_NAME = $BRANCH ]; then bower install --allow-root && gulp clean && gulp build && mv dist public; fi
  artifacts:
    paths:
    - public
  tags:
    - docker
  only:
    - master
    - staging

