baseURL = "/"
languageCode = "en-us"
title = "BlkSail Site"
theme = "blksail"

# The site's parameters
[params]
  home = "Home"
  
  [menu]

    [[menu.header]]
      weight = 2
      name = "Blog"
      url = "/Blog"
    
    [[menu.header]]
      weight = 5
      name = "Contact"
      url = "/contact"


   [params.bgVideo]
    enable = true
    vidBoat1 =  "img/boat_sail.mov"
    url = "#"

  

[params.wrapper]
    enable = true
    image = "img/beach12.mp4"
    title = "Completely autonomous in complex environments"
    paragraph = "Completely autonomous in complex environments, BLKSAIL is driving autonomously in ways that no one else has shown. We are driving in cities and on highways. Making unprotected lefts and rights on red. Yielding to pedestrians and passing double parked boats."

[params.iconsbox]
    enable = true
    title = "BLKSAIL is developing the future of autonomous boats, today."
    first_paragraph = "Zero-emissions "
    second_paragraph = "Fully autonomous "
    third_paragraph = "Mobility-as-a-service"
    bgImg = "img/background_image.jpg"

    [params.wrapper2]
    enable = true
    video = "img/boat_sailing2.mp4"
    title = "Completely autonomous in complex environments"
    paragraph = "Completely autonomous in complex environments, BLKSAIL is driving autonomously in ways that no one else has shown. We are driving in cities and on highways. Making unprotected lefts and rights on red. Yielding to pedestrians and passing double parked boats."

    [params.openPositions]
    title = "Some text goes here."


    [params.info]
    bgVideo="img/background_video.mp4"

    [[menu.footer]]
      weight = 1
      name = "About us"
      url = "#"
    [[menu.footer]]
      weight = 2
      name = "Contact us"
      url = "#"
    
    [[menu.footer]]
      weight = 4
      name = "Blog"
      url = "#"
    [[menu.footer]]
      weight = 5
      name = "Terms"
      url = "#"