baseURL = "/"
languageCode = "en-us"
title = "blkSAIL - Marine Autonomy As A Service"
theme = "blksail"

[menu]

  [[menu.header]]
    weight = 2
    name = "Blog"
    url = "/Blog"
    local = false

  [[menu.header]]
    weight = 5
    name = "Contact"
    url = "#contact-us"
    local = true

[params]
  home = "Home"
  logo = "/img/logo.svg"

  [params.bgVideo]
  enable = true
  vidBoat1 =  "img/boat_sail.mov"
  url = "#"

  [params.wrapper]
      enable = true
      image = "img/beach12.mp4"
      title = "SAIL INTO THE FUTURE WITH AUTONOMY"
      paragraph = "blkS▵IL is bringing Autonomy and Captain Assistance to the Maritime Industry. Hope on-board and be with the pioneers."

  [params.iconsbox]
      enable = true
      title = "blkS▵IL is developing future of Maritime, today."
      first_glyph = "fa-ship"
      first_paragraph = "Custom Built for the Maritime"
      second_glyph = "fa-compass"
      second_paragraph = "Auto-Pilot & DP Compatible"
      third_glyph = "fa-random"
      third_paragraph = "Modular & Customizable"
      bgImg = "img/background_image.jpg"

  [params.wrapper2]
    enable = true
    video = "img/boat_sailing2.mp4"
    title = "Autonomy for the Maritime is not just a gimmick, it is the game changer."
    paragraph = "Autonomy and Captain-Assistance will create new business models and potentially change the way marine operations are run forever. <br> blkS▵IL technology enables \"Just-In-Time\" sailing, fuel-savings, and reduces any risk of collision."



  [params.info]
    bgVideo="img/background_video.mp4"
    title ="FORGET ROBO-CARS AND HIT <br> THE WATER ON AN AUTONOMOUS BOAT"
    paragraph =" Large and small—self-piloting boats, could save fuel, prevent expensive accidents and groundings, and relieve crews of some of mundanity of life on the water."


  [params.contact]
    enable = true
    title = "Stay connected"
   


    [params.contact.box]
      address = "Your complete adresse + USA"
      map = "https://www.google.com/maps"
      mail = "contact@mail.com"
      phone = "+1 489 904 8 868 202 "


    [params.contact.social]
    facebook = "facebook url "
    fa_glyph = "fa-facebook"
    linkedIn = "Linkedin url "
    lkd_glyph ="fa-linkedin"
    instgram = " Insta url "
    insta_glyph ="fa-instagram"

