baseURL = "/"
languageCode = "en-us"
title = "blkSAIL - Marine Autonomy As A Service"
theme = "blksail"

[menu]

  [[menu.header]]
    weight = 5
    name = "Contact"
    url = "#contact-us"

[params]
  home = "Home"
  logo = "/img/logo.svg"

  [params.hero]
  enable = true
  video_url = "img/boat_sail.mov"

  [params.mission]
      enable = true
      title = "<span class=\"blk\">blk</span><span class=\"sail\">s▵il</span> is developing the future of Maritime, today."
      [[params.mission.item]]
        glyph = "fa-ship"
        description = "Custom Built for the Maritime"
      [[params.mission.item]]
        glyph = "fa-compass"
        description = "Auto-Pilot & DP Compatible"
      [[params.mission.item]]
        glyph = "fa-random"
        description = "Modular & Customizable"

  [params.splitVideos]
      enable = true
      [[params.splitVideos.video]]
        right_side = true
        video_url = "img/beach12.mp4"
        title = "Sail Into The Future With Autonomy"
        paragraph = "<span class=\"blk\">blk</span><span class=\"sail\">s▵il</span> is bringing Autonomy and Captain Assistance to the Maritime Industry. Hop on-board and join the pioneers."
      [[params.splitVideos.video]]
        right_side = false
        video_url = "img/boat_sailing2.mp4"
        title = "Autonomy for the Maritime is not just a gimmick, it is the game changer."
        paragraph = "<span class=\"blk\">blk</span><span class=\"sail\">s▵il</span> technology enables \"Just-In-Time\" sailing, fuel-savings, and reduces any risk of collision."

  [params.punch]
    video_url="img/background_video.mp4"
    title ="The -autonomous- ships are sailing,<br>time is running out."
    paragraph ="Autonomy and Captain-Assistance will create new business models and potentially change the way marine operations are run forever."


  [params.contact]
    enable = true
    title = "Stay connected!"

  [params.footer]
    [[params.footer.item]]
      text = "© blkSAIL LLC, 2019"
      url = "#"
    [[params.footer.item]]
      text = "contact@blksail.xyz"
      url = "mailto:contact@blksail.xyz"
